#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/../app"

# 1. A file importing ALL sources — without it lcov does not see files that no
#    test touches and "100%" would mean nothing. Generated, gitignored.
python3 - <<'EOF'
import pathlib
files = sorted(
    p for p in pathlib.Path("lib").rglob("*.dart") if not p.name.endswith(".g.dart")
)
lines = [
    "// GENERATED by scripts/check_coverage_app.sh - nie edytowac recznie.",
    "// ignore_for_file: unused_import, directives_ordering",
    "",
]
lines += [f"import 'package:droplet/{p.relative_to('lib').as_posix()}';" for p in files]
lines += ["", "void main() {}", ""]
pathlib.Path("test/all_imports_test.dart").write_text("\n".join(lines))
EOF

# 2. Tests with coverage
flutter test --coverage

# 3. 100% gate. Skipped: *.g.dart and files carrying `// coverage:ignore-file`
#    in the first 5 lines (allow-list: Global Constraints of the M4 plan).
python3 - <<'EOF'
import pathlib, re, sys

ALLOWED_IGNORE = re.compile(r"^lib/core/platform/[a-z_]+_port\.dart$")
covered = total = 0
record_file = ""
skip = False
missing = {}
with open("coverage/lcov.info") as f:
    for line in f:
        if line.startswith("SF:"):
            record_file = line.strip()[3:]
            head = "".join(pathlib.Path(record_file).read_text().splitlines(True)[:5])
            marked = "// coverage:ignore-file" in head
            if marked and not ALLOWED_IGNORE.match(record_file):
                print(f"ERROR: {record_file} ma coverage:ignore-file poza dozwolona lista")
                sys.exit(1)
            skip = record_file.endswith(".g.dart") or marked
            continue
        if skip:
            continue
        m = re.match(r"DA:(\d+),(\d+)", line)
        if m:
            total += 1
            if int(m.group(2)) > 0:
                covered += 1
            else:
                missing.setdefault(record_file, []).append(int(m.group(1)))
pct = 100.0 * covered / total if total else 100.0
print(f"coverage: {covered}/{total} lines = {pct:.2f}%")
for path, lines in missing.items():
    print(f"  MISSING {path}: {lines[:25]}{' ...' if len(lines) > 25 else ''}")
sys.exit(0 if pct >= 100.0 else 1)
EOF
