# Generated by Django 6.0.8 on 2026-09-01 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('libretro', 'Libretro'), ('manual', 'Manual')], max_length=10)),
                ('match_name', models.CharField(blank=True, max_length=500)),
                ('score', models.FloatField(default=0)),
                ('is_manual', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='library.game')),
            ],
        ),
    ]
