# Generated by Django 6.0.8 on 2026-09-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='source',
            field=models.CharField(choices=[('libretro', 'Libretro'), ('titledb', 'Titledb'), ('manual', 'Manual')], max_length=10),
        ),
    ]
